# Generated by Django 3.1.4 on 2021-02-26 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=350)),
                ('postcode', models.CharField(max_length=10)),
                ('location', models.CharField(choices=[('brighton', 'Brighton'), ('leeds', 'Leeds'), ('liverpool', 'Liverpool'), ('manchester', 'Manchester'), ('nottingham', 'Nottingham'), ('portsmouth', 'Portsmouth'), ('reading', 'Reading')], default=None, max_length=100)),
                ('alternate_location', models.CharField(blank=True, max_length=200)),
                ('cost', models.FloatField()),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('contact_mobile', models.CharField(blank=True, max_length=15)),
                ('contact_email', models.CharField(blank=True, max_length=255)),
                ('mirrors', models.BooleanField(default=False)),
                ('wooden_floor', models.BooleanField(default=False)),
                ('music_system', models.BooleanField(default=False)),
                ('floor_type', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_allowed', models.BooleanField(default=True)),
                ('venue_image', models.ImageField(default='dance_class.jpg', upload_to='venue_image/%Y/%m/%d')),
                ('venue_image_1', models.ImageField(blank=True, upload_to='venue_image/%Y/%m/%d')),
                ('venue_image_2', models.ImageField(blank=True, upload_to='venue_image/%Y/%m/%d')),
                ('slug', models.SlugField(default=None, editable=False)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
