# Generated by Django 3.1.7 on 2022-01-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_auto_20210410_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='venue_image/%Y/%m/%d'),
        ),
    ]
