# Generated by Django 3.1.7 on 2022-01-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_auto_20220101_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='about_venue',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
