# Generated by Django 3.1.7 on 2022-01-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_venue_about_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='size',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
