# Generated by Django 3.1.4 on 2020-12-31 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='media/users')),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True)),
                ('location', models.CharField(choices=[('brighton', 'Brighton'), ('leeds', 'Leeds'), ('liverpool', 'Liverpool'), ('manchester', 'Manchester'), ('nottingham', 'Nottingham'), ('portsmouth', 'Portsmouth'), ('reading', 'Reading')], default=None, max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
