# Generated by Django 3.1.4 on 2021-01-01 16:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201231_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_info',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, choices=[('brighton', 'Brighton'), ('leeds', 'Leeds'), ('liverpool', 'Liverpool'), ('manchester', 'Manchester'), ('nottingham', 'Nottingham'), ('portsmouth', 'Portsmouth'), ('reading', 'Reading')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='media/users/person_1.jpg', upload_to='media/users'),
        ),
    ]
