# Generated by Django 3.1.4 on 2021-01-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210104_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_image',
            field=models.ImageField(default='media/users/person_1.jpg', upload_to='media/company_images'),
        ),
        migrations.AddField(
            model_name='dancersprofile',
            name='dancers_image',
            field=models.ImageField(default='media/users/person_1.jpg', upload_to='media/dancers_images'),
        ),
    ]
