# Generated by Django 3.1.6 on 2021-02-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210104_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancersprofile',
            name='slug',
            field=models.SlugField(default=None, editable=False),
        ),
    ]
