# Generated by Django 3.1.7 on 2021-04-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_dancerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancersprofile',
            name='build',
            field=models.CharField(blank=True, choices=[('no_option', 'No Option'), ('slim', 'Slim'), ('medium', 'Medium'), ('muscular', 'Muscular'), ('large', 'Large')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dancersprofile',
            name='bust',
            field=models.IntegerField(blank=True, choices=[('50', '50 cm'), ('51', '51 cm'), ('52', '52 cm'), ('53', '53 cm'), ('54', '55 cm'), ('56', '56 cm'), ('57', '57 cm'), ('58', '58 cm'), ('59', '59 cm'), ('60', '60 cm'), ('61', '61 cm'), ('62', '62 cm'), ('63', '63 cm'), ('64', '64 cm'), ('65', '65 cm'), ('66', '66 cm'), ('67', '67 cm'), ('68', '68 cm'), ('69', '69 cm'), ('70', '70 cm'), ('71', '71 cm'), ('72', '72 cm'), ('73', '73 cm'), ('74', '74 cm'), ('75', '75 cm'), ('76', '76 cm'), ('77', '77 cm'), ('78', '78 cm'), ('79', '79 cm'), ('80', '80 cm'), ('81', '81 cm'), ('82', '82 cm'), ('83', '83 cm'), ('84', '84 cm'), ('85', '85 cm'), ('86', '86 cm'), ('87', '87 cm'), ('88', '88 cm'), ('89', '89 cm'), ('90', '90 cm'), ('91', '91 cm'), ('92', '92 cm'), ('93', '93 cm'), ('94', '94 cm'), ('95', '95 cm'), ('96', '96 cm'), ('97', '97 cm'), ('98', '98 cm'), ('99', '99 cm'), ('100', '100 cm'), ('101', '101 cm'), ('102', '102 cm'), ('103', '103 cm'), ('104', '104 cm'), ('105', '105 cm'), ('106', '106 cm'), ('107', '107 cm'), ('108', '108 cm'), ('109', '109 cm'), ('110', '110 cm'), ('111', '111 cm'), ('112', '112 cm'), ('113', '113 cm'), ('114', '114 cm'), ('115', '115 cm'), ('116', '116 cm'), ('117', '117 cm'), ('118', '118 cm'), ('119', '119 cm'), ('120', '120 cm'), ('121', '121 cm'), ('122', '122 cm'), ('123', '123 cm'), ('124', '124 cm'), ('125', '125 cm'), ('126', '126 cm'), ('127', '127 cm'), ('128', '128 cm'), ('129', '129 cm'), ('130', '130 cm'), ('131', '131 cm'), ('132', '132 cm'), ('133', '133 cm'), ('134', '134 cm'), ('135', '135 cm'), ('136', '136 cm'), ('137', '137 cm'), ('138', '138 cm'), ('139', '139 cm'), ('140', '140 cm'), ('141', '141 cm'), ('142', '142 cm'), ('143', '143 cm'), ('144', '144 cm'), ('145', '145 cm'), ('146', '146 cm'), ('147', '147 cm'), ('148', '148 cm'), ('149', '149 cm'), ('150', '150 cm')], default='0'),
        ),
        migrations.AddField(
            model_name='dancersprofile',
            name='eye',
            field=models.CharField(blank=True, choices=[('no_option', 'No Option'), ('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('hazel', 'Hazel'), ('grey', 'Grey'), ('green', 'Green')], default='no-option', max_length=20),
        ),
        migrations.AddField(
            model_name='dancersprofile',
            name='hair',
            field=models.CharField(blank=True, choices=[('no_option', 'No Option'), ('auburn', 'Auburn'), ('black', 'Black'), ('blonde', 'Blonde'), ('brown', 'Brown'), ('red', 'Red'), ('grey', 'Grey'), ('white', 'White')], default='no-option', max_length=20),
        ),
        migrations.AddField(
            model_name='dancersprofile',
            name='hip',
            field=models.IntegerField(blank=True, choices=[('50', '50 cm'), ('51', '51 cm'), ('52', '52 cm'), ('53', '53 cm'), ('54', '55 cm'), ('56', '56 cm'), ('57', '57 cm'), ('58', '58 cm'), ('59', '59 cm'), ('60', '60 cm'), ('61', '61 cm'), ('62', '62 cm'), ('63', '63 cm'), ('64', '64 cm'), ('65', '65 cm'), ('66', '66 cm'), ('67', '67 cm'), ('68', '68 cm'), ('69', '69 cm'), ('70', '70 cm'), ('71', '71 cm'), ('72', '72 cm'), ('73', '73 cm'), ('74', '74 cm'), ('75', '75 cm'), ('76', '76 cm'), ('77', '77 cm'), ('78', '78 cm'), ('79', '79 cm'), ('80', '80 cm'), ('81', '81 cm'), ('82', '82 cm'), ('83', '83 cm'), ('84', '84 cm'), ('85', '85 cm'), ('86', '86 cm'), ('87', '87 cm'), ('88', '88 cm'), ('89', '89 cm'), ('90', '90 cm'), ('91', '91 cm'), ('92', '92 cm'), ('93', '93 cm'), ('94', '94 cm'), ('95', '95 cm'), ('96', '96 cm'), ('97', '97 cm'), ('98', '98 cm'), ('99', '99 cm'), ('100', '100 cm'), ('101', '101 cm'), ('102', '102 cm'), ('103', '103 cm'), ('104', '104 cm'), ('105', '105 cm'), ('106', '106 cm'), ('107', '107 cm'), ('108', '108 cm'), ('109', '109 cm'), ('110', '110 cm'), ('111', '111 cm'), ('112', '112 cm'), ('113', '113 cm'), ('114', '114 cm'), ('115', '115 cm'), ('116', '116 cm'), ('117', '117 cm'), ('118', '118 cm'), ('119', '119 cm'), ('120', '120 cm'), ('121', '121 cm'), ('122', '122 cm'), ('123', '123 cm'), ('124', '124 cm'), ('125', '125 cm'), ('126', '126 cm'), ('127', '127 cm'), ('128', '128 cm'), ('129', '129 cm'), ('130', '130 cm'), ('131', '131 cm'), ('132', '132 cm'), ('133', '133 cm'), ('134', '134 cm'), ('135', '135 cm'), ('136', '136 cm'), ('137', '137 cm'), ('138', '138 cm'), ('139', '139 cm'), ('140', '140 cm'), ('141', '141 cm'), ('142', '142 cm'), ('143', '143 cm'), ('144', '144 cm'), ('145', '145 cm'), ('146', '146 cm'), ('147', '147 cm'), ('148', '148 cm'), ('149', '149 cm'), ('150', '150 cm')], default='0'),
        ),
        migrations.AddField(
            model_name='dancersprofile',
            name='location',
            field=models.CharField(choices=[('no_option', 'No Option'), ('bath', 'Bath'), ('birmingham', 'Birmingham'), ('blackpool', 'Blackpool'), ('bournemouth', 'Bournemouth'), ('brighton', 'Brighton'), ('bristol', 'Bristol'), ('cambridge', 'Cambridge'), ('canterbury', 'Canterbury'), ('cardiff', 'Cardiff'), ('chester', 'Chester'), ('coventry', 'Coventry'), ('derby', 'Derby'), ('durham', 'Durham'), ('eastbourne', 'Eastbourne'), ('edingurgh', 'Edinburgh'), ('exeter', 'Exeter'), ('glasgow', 'Glasgow'), ('harrogate', 'Harrogate'), ('hull', 'Hull'), ('ipswich', 'Ipswich'), ('kent', 'Kent'), ('lancaster', 'Lancaster'), ('leeds', 'Leeds'), ('leicester', 'Leicester'), ('liverpool', 'Liverpool'), ('london', 'london'), ('manchester', 'Manchester'), ('newcastle', 'Newcastle'), ('nottingham', 'Nottingham'), ('oxford', 'Oxford'), ('portsmouth', 'Portsmouth'), ('sheffield', 'Sheffield'), ('southampton', 'Southampton'), ('sunderland', 'Sunderland'), ('swansea', 'Swansea'), ('reading', 'Reading'), ('wolverhampton', 'Wolverhampton'), ('york', 'York')], default='no-option', max_length=100),
        ),
        migrations.AddField(
            model_name='dancersprofile',
            name='primary_job',
            field=models.CharField(blank=True, choices=[('no_option', 'No Option'), ('dancer', 'dancer'), ('dance_teacher', 'Dance Teacher'), ('choreographer', 'Choreographer')], default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='dancersprofile',
            name='waist',
            field=models.IntegerField(blank=True, choices=[('50', '50 cm'), ('51', '51 cm'), ('52', '52 cm'), ('53', '53 cm'), ('54', '55 cm'), ('56', '56 cm'), ('57', '57 cm'), ('58', '58 cm'), ('59', '59 cm'), ('60', '60 cm'), ('61', '61 cm'), ('62', '62 cm'), ('63', '63 cm'), ('64', '64 cm'), ('65', '65 cm'), ('66', '66 cm'), ('67', '67 cm'), ('68', '68 cm'), ('69', '69 cm'), ('70', '70 cm'), ('71', '71 cm'), ('72', '72 cm'), ('73', '73 cm'), ('74', '74 cm'), ('75', '75 cm'), ('76', '76 cm'), ('77', '77 cm'), ('78', '78 cm'), ('79', '79 cm'), ('80', '80 cm'), ('81', '81 cm'), ('82', '82 cm'), ('83', '83 cm'), ('84', '84 cm'), ('85', '85 cm'), ('86', '86 cm'), ('87', '87 cm'), ('88', '88 cm'), ('89', '89 cm'), ('90', '90 cm'), ('91', '91 cm'), ('92', '92 cm'), ('93', '93 cm'), ('94', '94 cm'), ('95', '95 cm'), ('96', '96 cm'), ('97', '97 cm'), ('98', '98 cm'), ('99', '99 cm'), ('100', '100 cm'), ('101', '101 cm'), ('102', '102 cm'), ('103', '103 cm'), ('104', '104 cm'), ('105', '105 cm'), ('106', '106 cm'), ('107', '107 cm'), ('108', '108 cm'), ('109', '109 cm'), ('110', '110 cm'), ('111', '111 cm'), ('112', '112 cm'), ('113', '113 cm'), ('114', '114 cm'), ('115', '115 cm'), ('116', '116 cm'), ('117', '117 cm'), ('118', '118 cm'), ('119', '119 cm'), ('120', '120 cm'), ('121', '121 cm'), ('122', '122 cm'), ('123', '123 cm'), ('124', '124 cm'), ('125', '125 cm'), ('126', '126 cm'), ('127', '127 cm'), ('128', '128 cm'), ('129', '129 cm'), ('130', '130 cm'), ('131', '131 cm'), ('132', '132 cm'), ('133', '133 cm'), ('134', '134 cm'), ('135', '135 cm'), ('136', '136 cm'), ('137', '137 cm'), ('138', '138 cm'), ('139', '139 cm'), ('140', '140 cm'), ('141', '141 cm'), ('142', '142 cm'), ('143', '143 cm'), ('144', '144 cm'), ('145', '145 cm'), ('146', '146 cm'), ('147', '147 cm'), ('148', '148 cm'), ('149', '149 cm'), ('150', '150 cm')], default='0'),
        ),
        migrations.AddField(
            model_name='dancersprofile',
            name='weight',
            field=models.IntegerField(blank=True, choices=[(10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100), (101, 101), (102, 102), (103, 103), (104, 104), (105, 105), (106, 106), (107, 107), (108, 108), (109, 109), (110, 110), (111, 111), (112, 112), (113, 113), (114, 114), (115, 115), (116, 116), (117, 117), (118, 118), (119, 119), (120, 120), (121, 121), (122, 122), (123, 123), (124, 124), (125, 125), (126, 126), (127, 127), (128, 128), (129, 129), (130, 130), (131, 131), (132, 132), (133, 133), (134, 134), (135, 135), (136, 136), (137, 137), (138, 138), (139, 139)], null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('no_option', 'No Option'), ('bath', 'Bath'), ('birmingham', 'Birmingham'), ('blackpool', 'Blackpool'), ('bournemouth', 'Bournemouth'), ('brighton', 'Brighton'), ('bristol', 'Bristol'), ('cambridge', 'Cambridge'), ('canterbury', 'Canterbury'), ('cardiff', 'Cardiff'), ('chester', 'Chester'), ('coventry', 'Coventry'), ('derby', 'Derby'), ('durham', 'Durham'), ('eastbourne', 'Eastbourne'), ('edingurgh', 'Edinburgh'), ('exeter', 'Exeter'), ('glasgow', 'Glasgow'), ('harrogate', 'Harrogate'), ('hull', 'Hull'), ('ipswich', 'Ipswich'), ('kent', 'Kent'), ('lancaster', 'Lancaster'), ('leeds', 'Leeds'), ('leicester', 'Leicester'), ('liverpool', 'Liverpool'), ('london', 'london'), ('manchester', 'Manchester'), ('newcastle', 'Newcastle'), ('nottingham', 'Nottingham'), ('oxford', 'Oxford'), ('portsmouth', 'Portsmouth'), ('sheffield', 'Sheffield'), ('southampton', 'Southampton'), ('sunderland', 'Sunderland'), ('swansea', 'Swansea'), ('reading', 'Reading'), ('wolverhampton', 'Wolverhampton'), ('york', 'York')], default=None, max_length=100, null=True),
        ),
    ]
