# Generated by Django 3.1.7 on 2021-04-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210412_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancersprofile',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('no-option', 'No Option'), ('asian-indian', 'Asian - Indian'), ('asian-other', 'Asian - Other'), ('asian-south-east', 'Asian - South East'), ('black', 'Black'), ('black-other', 'Black - Other'), ('caucasian', 'Caucasian'), ('caucasian-other', 'Caucasian - Other'), ('mediterranean', 'Mediterranean'), ('middle-eastern', 'Middle Eastern'), ('mixed', 'Mixed'), ('mixed', 'Mixed'), ('other', 'Other')], default='no-option', max_length=30),
        ),
    ]
