# Generated by Django 3.1.7 on 2021-04-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_dancersprofile_ethnicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancersprofile',
            name='skin',
            field=models.CharField(blank=True, choices=[('no-option', 'No Option'), ('black', 'Black'), ('brown', 'Brown'), ('olive', 'Olive'), ('tanned', 'Tanned'), ('white', 'White'), ('other', 'Other')], default='no-option', max_length=30),
        ),
    ]
