# Generated by Django 3.1.7 on 2021-05-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
