# Generated by Django 3.1.7 on 2022-08-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210905_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dancersprofile',
            name='build',
        ),
        migrations.RemoveField(
            model_name='dancersprofile',
            name='bust',
        ),
        migrations.RemoveField(
            model_name='dancersprofile',
            name='dress',
        ),
        migrations.RemoveField(
            model_name='dancersprofile',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='dancersprofile',
            name='eye',
        ),
        migrations.RemoveField(
            model_name='dancersprofile',
            name='hair',
        ),
        migrations.RemoveField(
            model_name='dancersprofile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='dancersprofile',
            name='hip',
        ),
        migrations.RemoveField(
            model_name='dancersprofile',
            name='skin',
        ),
        migrations.RemoveField(
            model_name='dancersprofile',
            name='waist',
        ),
        migrations.RemoveField(
            model_name='dancersprofile',
            name='weight',
        ),
    ]
