# Generated by Django 3.1.7 on 2022-08-01 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20220801_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_dancer',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_employer',
        ),
    ]
