# Generated by Django 3.1.7 on 2021-04-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210112_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(choices=[('no_option', 'No Option'), ('bath', 'Bath'), ('birmingham', 'Birmingham'), ('blackpool', 'Blackpool'), ('bournemouth', 'Bournemouth'), ('brighton', 'Brighton'), ('bristol', 'Bristol'), ('cambridge', 'Cambridge'), ('canterbury', 'Canterbury'), ('cardiff', 'Cardiff'), ('chester', 'Chester'), ('coventry', 'Coventry'), ('derby', 'Derby'), ('durham', 'Durham'), ('eastbourne', 'Eastbourne'), ('edingurgh', 'Edinburgh'), ('exeter', 'Exeter'), ('glasgow', 'Glasgow'), ('harrogate', 'Harrogate'), ('hull', 'Hull'), ('ipswich', 'Ipswich'), ('kent', 'Kent'), ('lancaster', 'Lancaster'), ('leeds', 'Leeds'), ('leicester', 'Leicester'), ('liverpool', 'Liverpool'), ('london', 'london'), ('manchester', 'Manchester'), ('newcastle', 'Newcastle'), ('nottingham', 'Nottingham'), ('oxford', 'Oxford'), ('portsmouth', 'Portsmouth'), ('sheffield', 'Sheffield'), ('southampton', 'Southampton'), ('sunderland', 'Sunderland'), ('swansea', 'Swansea'), ('reading', 'Reading'), ('wolverhampton', 'Wolverhampton'), ('york', 'York')], default=None, max_length=100),
        ),
    ]
