# Generated by Django 3.1.7 on 2021-11-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210410_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rehearsal_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
