# Generated by Django 3.1.4 on 2020-12-30 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyBalletClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('location', models.CharField(choices=[('brighton', 'Brighton'), ('leeds', 'Leeds'), ('liverpool', 'Liverpool'), ('manchester', 'Manchester'), ('nottingham', 'Nottingham'), ('portsmouth', 'Portsmouth'), ('reading', 'Reading')], default=None, max_length=100)),
                ('course_level', models.CharField(choices=[('complete_beginners', 'Complete Beginnes'), ('beginners', 'Beginners'), ('general', 'General'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('Professional', 'Professional')], default=None, max_length=50)),
                ('age_group', models.CharField(choices=[('complete_beginners', 'Complete Beginnes'), ('beginners', 'Beginners'), ('general', 'General'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('Professional', 'Professional')], default=None, max_length=50)),
                ('day', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('eednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], default=None, max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('address', models.CharField(max_length=350)),
                ('postcode', models.CharField(max_length=15)),
                ('price', models.FloatField()),
                ('faq', models.TextField()),
                ('clothes', models.CharField(blank=True, max_length=300)),
                ('experience', models.CharField(blank=True, max_length=300)),
                ('average_age', models.CharField(blank=True, max_length=300)),
                ('drop_in', models.CharField(blank=True, max_length=300)),
                ('about_dance_class', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('is_allowed', models.BooleanField(default=True)),
                ('dance_class_image', models.ImageField(default='dance_class.jpg', upload_to='dance_class_image/%Y/%m/%d')),
                ('dance_class_image_1', models.ImageField(blank=True, upload_to='dance_class_image/%Y/%m/%d')),
                ('dance_class_image_2', models.ImageField(blank=True, upload_to='dance_class_image/%Y/%m/%d')),
                ('dance_class_image_3', models.ImageField(blank=True, upload_to='dance_class_image/%Y/%m/%d')),
                ('slug', models.SlugField(default=None, editable=False)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
