# Generated by Django 3.1.4 on 2020-12-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyballetclass',
            name='age_group',
            field=models.CharField(choices=[('toddlers', 'Toddlers'), ('children', 'Children'), ('teens', 'Teens'), ('adults', 'Adults')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='weeklyballetclass',
            name='day',
            field=models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], default=None, max_length=20),
        ),
    ]
