# Generated by Django 3.1.4 on 2020-12-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20201230_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyballetclass',
            name='teacher',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='weeklyballetclass',
            name='course_level',
            field=models.CharField(choices=[('complete_beginners', 'Complete Beginners'), ('beginners', 'Beginners'), ('general', 'General'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('Professional', 'Professional')], default=None, max_length=50),
        ),
    ]
