# Generated by Django 3.1.4 on 2021-03-13 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201230_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyballetclass',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyballetclass',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
