# Generated by Django 3.1.4 on 2021-03-27 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_coursereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballet_classes', to='courses.weeklyballetclass'),
        ),
    ]
