# Generated by Django 3.1.5 on 2021-01-19 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='conversations', to='mail.conversation'),
        ),
    ]
