# Generated by Django 3.1.5 on 2021-01-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20210119_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='messenger_1_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='messenger_2_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
