# Generated by Django 3.1.5 on 2021-01-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20210120_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='messenger_1_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='messenger_2_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
