# Generated by Django 3.1.4 on 2021-03-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_auto_20210129_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='category',
            field=models.CharField(blank=True, choices=[('talent', 'talent'), ('venue', 'venue'), ('jobs', 'jobs'), ('course', 'course'), ('general', 'general')], default=None, max_length=50, null=True),
        ),
    ]
